inherits = 'autumn'

[palette]

my_black      = "#101010" # Cursorline
my_gray0      = "#1C1C1C" # Default Background
my_gray1      = "#2b2b2b" # Ruler
my_gray2      = "#323232" # Lighter Background (Used for status bars, line number and folding marks)
my_gray3      = "#3d3d3d" # Selection Background
my_gray4      = "#7c7c7c" # Comments, Invisibles, Line Highlighting
my_gray5      = "#a8a8a8" # Dark Foreground (Used for status bars)
my_gray6      = "#c8c8c8" # Light Foreground (Not often used)
